
import { uniqueId } from 'lodash';

import {
  IconCopy, IconLayoutDashboard, IconMoodHappy, IconTypography, IconFileUpload, IconCalendarEvent, IconClipboardList, IconGavel, IconUsers,
  IconAward,
  IconBoxMultiple,
  IconPoint,
  IconAlertCircle,
  IconNotes,
  IconCalendar,
  IconMail,
  IconTicket,
  IconEdit,
  IconCurrencyDollar,
  IconApps,
  IconFileDescription,
  IconFileDots,
  IconFiles,
  IconBan,
  IconStar,
  IconMoodSmile,
  IconBorderAll,
  IconBorderHorizontal,
  IconBorderInner,
  IconBorderVertical,
  IconBorderTop,
  IconUserCircle,
  IconPackage,
  IconMessage2,
  IconBasket,
  IconChartLine,
  IconChartArcs,
  IconChartCandle,
  IconChartArea,
  IconChartDots,
  IconChartDonut3,
  IconChartRadar,
  IconLogin,
  IconUserPlus,
  IconRotate,
  IconBox,
  IconShoppingCart,
  IconAperture,
  IconLayout,
  IconSettings,
  IconHelp,
  IconZoomCode,
  IconBoxAlignBottom,
  IconBoxAlignLeft,
  IconBorderStyle2,
  IconAppWindow,
  IconNotebook,
  IconFileCheck,
  IconChartHistogram,
  IconChartPie2,
  IconChartScatter,
  IconChartPpf,
  IconChartArcs3,
  IconListTree,
  IconArrowsExchange,
  IconLayoutSidebar,
  IconLock, IconAlignBoxLeftBottom, IconCheckbox, IconRadar, IconSlideshow, IconCaretUpDown, IconTable, IconForms
} from '@tabler/icons-react';

// Roles: ADMIN, PAUTISTA, AVALIADOR
// PAUTISTA/AVALIADOR: Dashboard, Pautas, Audiências
// ADMIN: Todas as rotas

const Menuitems = [
  {
    navlabel: true,
    subheader: 'Home',
  },

  {
    id: uniqueId(),
    title: 'Dashboard',
    icon: IconLayoutDashboard,
    href: '/dashboard',
    roles: ['PAUTISTA', 'AVALIADOR', 'ADMIN','APOIO'],
  },
  {
    id: uniqueId(),
    title: 'Upload de Audiências',
    icon: IconFileUpload,
    href: '/upload-planilha',
    roles: ['ADMIN', 'APOIO'],
  },
  {
    id: uniqueId(),
    title: 'Equipe',
    icon: IconUsers,
    roles: ['ADMIN', 'APOIO'],
    children: [
      {
        id: uniqueId(),
        title: 'Avaliadores',
        href: '/equipe/avaliadores',
        roles: ['ADMIN','APOIO'],
      },
      {
        id: uniqueId(),
        title: 'Pautistas',
        href: '/equipe/pautistas',
        roles: ['ADMIN','APOIO'],
      },
      {
        id: uniqueId(),
        title: 'Apoio',
        href: '/equipe/apoio',
        roles: ['ADMIN', 'APOIO'],
      },
    ],
  },
  {
    id: uniqueId(),
    title: 'Escala',
    icon: IconCalendarEvent,
    href: '/escala',
    roles: ['ADMIN', 'APOIO'],
  },
  {
    id: uniqueId(),
    title: 'Controle de Escala',
    icon: IconArrowsExchange,
    href: '/escala/controle',
    roles: ['ADMIN'],
  },
  {
    id: uniqueId(),
    title: 'Pautas',
    icon: IconClipboardList,
    href: '/pautas',
    roles: ['PAUTISTA', 'AVALIADOR', 'ADMIN','APOIO'],
  },
  {
    id: uniqueId(),
    title: 'Consulta de Audiencias',
    icon: IconGavel,
    href: '/audiencias',
    roles: ['PAUTISTA', 'AVALIADOR', 'ADMIN','APOIO'],
  },
  {
    id: uniqueId(),
    title: 'Relatório',
    icon: IconChartHistogram,
    href: '/relatorio',
    roles: ['ADMIN', 'APOIO'],
    chip: 'Novo',
  },
  {
    id: uniqueId(),
    title: 'Controle de Usuários',
    icon: IconSettings,
    href: '/usuarios',
    roles: ['ADMIN'],
  }
];

export default Menuitems;
